DROP TABLE IF EXISTS BANNER;
CREATE TABLE BANNER (
ID INT NOT NULL AUTO_INCREMENT
, TITLE VARCHAR(100) NOT NULL
, TEXT VARCHAR(2000)
, LINK VARCHAR(2048)
, PHOTO BLOB
, VERSION INT NOT NULL DEFAULT 0
, PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TAB;
CREATE TABLE TAB (
ID INT NOT NULL AUTO_INCREMENT
, TITLE VARCHAR(100) NOT NULL
, TEXT VARCHAR(2000)
, PHOTO BLOB
, PARENT_ID INT DEFAULT 0
, VERSION INT NOT NULL DEFAULT 0
, PRIMARY KEY (ID)
);